name: 'Google Repo Checkout'
description: 'Downloads a Google Repo'
inputs:
  repo-url:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true
  origin-repo:
    description: 'Origin repository with owner'
    default: ${{ github.repository }}
  checkout-deps:
    description: 'Checkouts the dependencies for the origin repo and branch'
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo-url }}
    - ${{ inputs.checkout-deps }}
    - ${{ inputs.origin-repo }}
