name: 'Google Repo Checkout'
description: 'Downloads a Google Repo'
inputs:
  repo-url:  # id of input
    description: 'repo url'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo-url }}
