name: 'Google Repo Checkout'
description: 'Downloads a Google Repo'
inputs:
  manifest-url:
    description: 'Manifest repository name with owner. For example, actions/checkout'
    required: true
  manifest-branch:
    description: 'Manifest branch where to find the xml manifest file'
    default: 'refs/heads/main'
  manifest-file:
    description: 'Manifest file (to override default.xml)'
    default: 'default.xml'
  manifest-group:
    description: 'Selects the manifest group when syncing the code'
    default: 'default'
  origin-repo:
    description: 'Origin repository with owner'
    default: ${{ github.repository }}
  checkout-deps:
    description: 'Checkouts the dependencies for the origin repo and branch'
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.manifest-url }}
    - ${{ inputs.manifest-branch }}
    - ${{ inputs.manifest-file }}
    - ${{ inputs.manifest-group }}
    - ${{ inputs.checkout-deps }}
    - ${{ inputs.origin-repo }}
